# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
target 'CheckVersionTest' do
	pod 'Alamofire', '~> 3.4'
	pod 'Kanna', '~> 1.0.0'
	
end
